---
os: osx

before_install:
  # - yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
  # - sudo rm -rf /usr/local/Caskroom
  # - sudo rm -rf /usr/local/Cellar
  - ./scripts/travis_macos_brew_cache.sh
  - ./scripts/python.sh
  - ./scripts/venv.sh
  - source .venv/bin/activate
  - pip install -r requirements.txt &> /dev/null

cache:
  directories:
    - .venv
    - $HOME/Library/Caches/Homebrew

before_cache:
  - brew cleanup

env:
  matrix: 
  - TEST_VAR="js_homebrewcask_mactex_enabled=True"
  - TEST_VAR="js_homebrewcask_java_enabled=True"
  - TEST_VAR="js_homebrewcask_docker_enabled=True"
  - TEST_VAR="js_homebrewcask_iterm2_enabled=True"
  - TEST_VAR="js_homebrewcask_googlechrome_enabled=True"
  - TEST_VAR="js_homebrewcask_sublimetext3_enabled=True"
  - TEST_VAR="js_homebrewcask_atom_enabled=True"
  - TEST_VAR="js_homebrewcask_visualstudiocode_enabled=True"
  - TEST_VAR="js_homebrewcask_fontfiracode_enabled=True"
  - TEST_VAR="js_homebrewcask_gpgsuite_enabled=True"
  - TEST_VAR="js_homebrewcask_slack_enabled=True"
  - TEST_VAR="js_homebrewcask_discord_enabled=True"
  - TEST_VAR="js_homebrewpackage_zsh_enabled=True"
  - TEST_VAR="js_homebrewpackage_zshtheme_spaceship_enabled=True"
  - TEST_VAR="js_homebrewpackage_python_enabled=True"
  - TEST_VAR="js_homebrewpackage_git_enabled=True"
  - TEST_VAR="js_homebrewpackage_node_enabled=True"

script:
  - ./tests/test.sh
