---
- name: Updating Homebrew
  homebrew:
    update_homebrew: yes

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: yes

- import_tasks: zsh.yml
  when: js_homebrewpackage_zsh_enabled

- import_tasks: zsh_spaceship.yml
  when: js_homebrewpackage_zshtheme_spaceship_enabled
  
