---
- name: Ensuring zsh is installed
  homebrew:
    name: zsh

- name: Cloning Spaceship Prompt repository
  shell: git clone https://github.com/denysdovhan/spaceship-prompt.git "{{ lookup('env', 'ZSH_CUSTOM') }}/themes/spaceship-prompt"

- name: Symlink spaceship.zsh-theme to oh-my-zsh custom themes directory
  shell: ln -s "{{ lookup('env', 'ZSH_CUSTOM') }}/themes/spaceship-prompt/spaceship.zsh-theme" "{{ lookup('env', 'ZSH_CUSTOM') }}/themes/spaceship.zsh-theme"

- name: Changing theme in .zshrc
  lineinfile: 
    path: "~/.zshrc"
    regexp: "^ZSH_THEME"
    line: "ZSH_THEME=\"spaceship\""