---
- name: Ensuring zsh is installed
  homebrew:
    name: zsh

- name: Changing to zsh shell
  become: yes
  user: 
    name: "{{ ansible_user_id }}"
    shell: "/bin/zsh"
  
- name: Get ZSH Path
  setup: 

- name: Cloning Spaceship Prompt repository
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "$ZSH/custom/themes/spaceship-prompt"

- name: Symlink spaceship.zsh-theme to oh-my-zsh custom themes directory
  shell: ln -s "$ZSH/custom/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH/custom/themes/spaceship.zsh-theme"
  args:
    executable: /bin/zsh
    
- name: Changing theme in .zshrc
  lineinfile: 
    path: "~/.zshrc"
    regexp: "^ZSH_THEME"
    line: "ZSH_THEME=\"spaceship\""