---
- name: Ensuring Homebrew is installed
  stat:
    path: "/usr/local/bin/brew"
  register: "check_homebrew"

- name: Installing Homebrew
  command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: is_CI|default(False) == False

- name: Updating Homebrew
  homebrew: 
    update_homebrew: true
  when: is_CI|default(False) == False

- name: Upgrading Homebrew
  when: is_travis is not defined
  homebrew:
    upgrade_all: true
  when: is_CI|default(False) == False

- name: Ensuring ~/.bash_profile exists
  file: 
    path: ~/.bash_profile
    state: touch

- name: Using Homebrew packages by default
  lineinfile: 
    path: ~/.bash_profile
    regexp: '^export PATH="/usr/local/bin:\$PATH"'
    line: 'export PATH="/usr/local/bin:$PATH"'