---
- name: Install Sublime Text 3 through Homebrew
  homebrew_cask:
    name: sublime-text
    install_options: 'appdir=/Applications'

- name: Configuring Sublime Text 3
  copy:
    src: "{{ role_path }}/files/Preferences.sublime-settings"
    dest: "~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings"
