---
- name: Customize Jumpstart Installation
  hosts: system
  gather_facts: no
  

  vars_prompt:
    - name: js_understand_default
      prompt: "For the following, press enter for the default value in"
      default: "square brackets"
      private: no
    - name: js_homebrewpackage_zsh_enabled
      prompt: "Would you like to install the Z shell (zsh)? Press enter for default"
      default: "yes"
      private: no

  tasks:
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zsh_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zsh_enabled: {{ js_homebrewpackage_zsh_enabled|bool }}"
      