---
- name: Customize Jumpstart Installation
  hosts: system
  gather_facts: no
  

  vars_prompt:
    - name: js_understand_default
      prompt: "We will now go through Command Line Tools..."
      default: "yes"
    - name: js_homebrewpackage_zsh_enabled
      prompt: "Would you like to install the Z shell (zsh)?"
      default: "yes"
    - name: js_homebrewpackage_zshtheme_spaceship_enabled
      prompt: "Would you like to set the Zsh theme to spaceship?"
      default: "yes"
    - name: js_homebrewpackage_python_enabled
      prompt: "Would you like to install Python?"
      default: "yes"
    - name: js_homebrewpackage_git_enabled
      prompt: "Would you like to install Git?"
      default: "yes"
    - name: js_understand_default
      prompt: "We will now go through General Applications and Tools..."
      default: "yes"
    - name: js_homebrewcask_iterm2_enabled
      prompt: "Would you like to install iTerm2?"
      default: "yes"
    - name: js_homebrewcask_sublimetext3_enabled
      prompt: "Would you like to install Sublime Text 3?"
      default: "yes"
    - name: js_homebrewcask_atom_enabled
      prompt: "Would you like to install Atom?"
      default: "yes"
    - name: js_homebrewcask_gpgsuite_enabled
      prompt: "Would you like to install GPG Suite?"
      default: "yes"

  tasks:
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zsh_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zsh_enabled: {{ js_homebrewpackage_zsh_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zshtheme_spaceship_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zshtheme_spaceship_enabled: {{ js_homebrewpackage_zshtheme_spaceship_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_python_enabled: (?:True|False)$"
        line: "js_homebrewpackage_python_enabled: {{ js_homebrewpackage_python_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_git_enabled: (?:True|False)$"
        line: "js_homebrewpackage_git_enabled: {{ js_homebrewpackage_git_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_iterm2_enabled: (?:True|False)$"
        line: "js_homebrewcask_iterm2_enabled: {{ js_homebrewcask_iterm2_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_sublimetext3_enabled: (?:True|False)$"
        line: "js_homebrewcask_sublimetext3_enabled: {{ js_homebrewcask_sublimetext3_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_atom_enabled: (?:True|False)$"
        line: "js_homebrewcask_atom_enabled: {{ js_homebrewcask_atom_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_gpgsuite_enabled: (?:True|False)$"
        line: "js_homebrewcask_gpgsuite_enabled: {{ js_homebrewcask_gpgsuite_enabled|bool }}"