---
- name: Customize macOS Developer Setup Installation
  hosts: system
  gather_facts: no

  vars_prompt:
    - name: devsetup_main_homebrew_enabled
      prompt: "Would you like to install Homebrew? Press enter for default "
      default: "yes"
      private: no
    - name: devsetup_homebrew_package_zsh_enabled
      prompt: "Would you like to install the Z shell (zsh)? Press enter for default "
      default: "yes"
      private: no
    - name: devsetup_homebrew_package

  tasks:
    - lineinfile:
        path: "../vars/vars.yml"
        regexp: "^devsetup_main_homebrew_enabled: (?:True|False)$"
        line: "devsetup_main_homebrew_enabled: {{ devsetup_main_homebrew_enabled|bool }}"
    - lineinfile:
        path: "../vars/vars.yml"
        regexp: "^devsetup_homebrew_package_zsh_enabled: (?:True|False)$"
        line: "devsetup_homebrew_package_zsh_enabled: {{ devsetup_homebrew_package_zsh_enabled|bool }}"
      