---
- name: Customize Jumpstart Installation
  hosts: system
  gather_facts: no
  

  vars_prompt:
    - name: js_understand_default
      prompt: "For the following, press enter for the default value"
      default: "yes"
      private: no
    - name: js_homebrewpackage_zsh_enabled
      prompt: "Would you like to install the Z shell (zsh)?"
      default: "yes"
      private: no
    - name: js_homebrewpackage_zshtheme_spaceship_enabled
      prompt: "Would you like to set the Zsh theme to spaceship?"
      default: "yes"
    - name: js_homebrewcask_iterm2_enabled
      prompt: "Would you like to install iTerm2?"
      default: "yes"

    

  tasks:
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zsh_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zsh_enabled: {{ js_homebrewpackage_zsh_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewpackage_zshtheme_spaceship_enabled: (?:True|False)$"
        line: "js_homebrewpackage_zshtheme_spaceship_enabled: {{ js_homebrewpackage_zshtheme_spaceship_enabled|bool }}"
    - lineinfile:
        path: "../global_vars/vars.yml"
        regexp: "^js_homebrewcask_iterm2_enabled: (?:True|False)$"
        line: "js_homebrewcask_iterm2_enabled: {{ js_homebrewcask_iterm2_enabled|bool }}"
        